// api/foods.js — 식재료 DB 내장 버전
const FOODS = [
  {
    "name": "닭가슴살(생)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 109.0,
    "protein": 23.1,
    "carb": 0.0,
    "fat": 1.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "닭안심(생)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 105.0,
    "protein": 22.5,
    "carb": 0.0,
    "fat": 1.0,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "계란(전란)",
    "category": "단백질",
    "unit": "개",
    "amount": 60.0,
    "kcal": 83.0,
    "protein": 7.3,
    "carb": 0.6,
    "fat": 5.7,
    "meals": "아침,간식",
    "note": "1개=60g"
  },
  {
    "name": "달걀흰자",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 48.0,
    "protein": 10.9,
    "carb": 0.7,
    "fat": 0.2,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "연어(생)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 208.0,
    "protein": 20.4,
    "carb": 0.0,
    "fat": 13.4,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "참치(캔,물)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 96.0,
    "protein": 21.5,
    "carb": 0.0,
    "fat": 0.5,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "소고기(우둔)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 143.0,
    "protein": 20.7,
    "carb": 0.0,
    "fat": 6.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "돼지고기(안심)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 143.0,
    "protein": 21.5,
    "carb": 0.0,
    "fat": 5.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "두부(일반)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 79.0,
    "protein": 8.2,
    "carb": 1.6,
    "fat": 4.4,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "연두부",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 42.0,
    "protein": 4.3,
    "carb": 1.5,
    "fat": 2.0,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "그릭요거트(무지방)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 59.0,
    "protein": 10.2,
    "carb": 3.6,
    "fat": 0.4,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "단백질쉐이크",
    "category": "단백질",
    "unit": "스쿱",
    "amount": 30.0,
    "kcal": 110.0,
    "protein": 22.0,
    "carb": 3.0,
    "fat": 1.5,
    "meals": "간식",
    "note": "1스쿱=30g"
  },
  {
    "name": "닭가슴살 소시지",
    "category": "단백질",
    "unit": "개",
    "amount": 45.0,
    "kcal": 56.0,
    "protein": 9.5,
    "carb": 1.2,
    "fat": 1.4,
    "meals": "간식",
    "note": ""
  },
  {
    "name": "새우(생)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 84.0,
    "protein": 19.0,
    "carb": 0.2,
    "fat": 0.6,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "고등어(생)",
    "category": "단백질",
    "unit": "g",
    "amount": 100.0,
    "kcal": 183.0,
    "protein": 18.8,
    "carb": 0.1,
    "fat": 11.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "현미밥",
    "category": "탄수화물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 167.0,
    "protein": 3.0,
    "carb": 36.4,
    "fat": 0.7,
    "meals": "점심,저녁",
    "note": "공기=210g"
  },
  {
    "name": "잡곡밥",
    "category": "탄수화물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 160.0,
    "protein": 3.2,
    "carb": 34.5,
    "fat": 0.8,
    "meals": "점심,저녁",
    "note": "공기=210g"
  },
  {
    "name": "흰쌀밥",
    "category": "탄수화물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 175.0,
    "protein": 2.7,
    "carb": 38.5,
    "fat": 0.3,
    "meals": "점심,저녁",
    "note": "공기=210g"
  },
  {
    "name": "고구마(생)",
    "category": "탄수화물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 130.0,
    "protein": 1.5,
    "carb": 31.0,
    "fat": 0.1,
    "meals": "아침,간식,저녁",
    "note": ""
  },
  {
    "name": "감자(생)",
    "category": "탄수화물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 68.0,
    "protein": 1.7,
    "carb": 15.6,
    "fat": 0.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "오트밀(생)",
    "category": "탄수화물",
    "unit": "g",
    "amount": 50.0,
    "kcal": 189.0,
    "protein": 6.5,
    "carb": 33.5,
    "fat": 3.4,
    "meals": "아침",
    "note": "1회=50g"
  },
  {
    "name": "바나나",
    "category": "탄수화물",
    "unit": "개",
    "amount": 100.0,
    "kcal": 93.0,
    "protein": 1.2,
    "carb": 22.1,
    "fat": 0.2,
    "meals": "아침,간식",
    "note": "1개=100g"
  },
  {
    "name": "사과",
    "category": "탄수화물",
    "unit": "개",
    "amount": 150.0,
    "kcal": 83.0,
    "protein": 0.5,
    "carb": 21.5,
    "fat": 0.2,
    "meals": "간식",
    "note": "1개=150g"
  },
  {
    "name": "통밀식빵",
    "category": "탄수화물",
    "unit": "장",
    "amount": 30.0,
    "kcal": 74.0,
    "protein": 3.0,
    "carb": 13.5,
    "fat": 0.9,
    "meals": "아침",
    "note": "1장=30g"
  },
  {
    "name": "옥수수(삶은)",
    "category": "탄수화물",
    "unit": "개",
    "amount": 150.0,
    "kcal": 154.0,
    "protein": 5.3,
    "carb": 32.7,
    "fat": 2.1,
    "meals": "간식",
    "note": "1개=150g"
  },
  {
    "name": "브로콜리(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 34.0,
    "protein": 2.8,
    "carb": 5.2,
    "fat": 0.4,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "시금치(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 20.0,
    "protein": 2.9,
    "carb": 1.8,
    "fat": 0.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "양배추(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 28.0,
    "protein": 1.7,
    "carb": 5.1,
    "fat": 0.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "오이(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 14.0,
    "protein": 0.7,
    "carb": 2.5,
    "fat": 0.1,
    "meals": "간식,저녁",
    "note": ""
  },
  {
    "name": "방울토마토",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 20.0,
    "protein": 0.9,
    "carb": 3.9,
    "fat": 0.2,
    "meals": "간식",
    "note": ""
  },
  {
    "name": "상추(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 16.0,
    "protein": 1.4,
    "carb": 2.1,
    "fat": 0.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "파프리카(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 28.0,
    "protein": 1.0,
    "carb": 5.9,
    "fat": 0.2,
    "meals": "간식,저녁",
    "note": ""
  },
  {
    "name": "당근(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 42.0,
    "protein": 0.9,
    "carb": 9.4,
    "fat": 0.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "양파(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 38.0,
    "protein": 1.1,
    "carb": 8.6,
    "fat": 0.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "버섯(새송이)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 34.0,
    "protein": 2.7,
    "carb": 5.5,
    "fat": 0.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "아보카도",
    "category": "지방",
    "unit": "개",
    "amount": 150.0,
    "kcal": 238.0,
    "protein": 3.0,
    "carb": 12.8,
    "fat": 21.9,
    "meals": "아침",
    "note": "1/2개=75g"
  },
  {
    "name": "아몬드",
    "category": "지방",
    "unit": "g",
    "amount": 20.0,
    "kcal": 116.0,
    "protein": 4.3,
    "carb": 4.4,
    "fat": 10.0,
    "meals": "간식",
    "note": "1줌=20g"
  },
  {
    "name": "올리브오일",
    "category": "지방",
    "unit": "ml",
    "amount": 10.0,
    "kcal": 88.0,
    "protein": 0.0,
    "carb": 0.0,
    "fat": 10.0,
    "meals": "조리용",
    "note": "1Ts=10ml"
  },
  {
    "name": "견과류믹스",
    "category": "지방",
    "unit": "g",
    "amount": 20.0,
    "kcal": 120.0,
    "protein": 3.5,
    "carb": 5.0,
    "fat": 10.5,
    "meals": "간식",
    "note": "1줌=20g"
  },
  {
    "name": "치즈(슬라이스)",
    "category": "지방",
    "unit": "장",
    "amount": 18.0,
    "kcal": 54.0,
    "protein": 3.8,
    "carb": 0.5,
    "fat": 4.2,
    "meals": "아침,간식",
    "note": "1장=18g"
  },
  {
    "name": "우유(저지방)",
    "category": "유제품",
    "unit": "ml",
    "amount": 200.0,
    "kcal": 86.0,
    "protein": 6.8,
    "carb": 9.2,
    "fat": 2.0,
    "meals": "아침,간식",
    "note": "1컵=200ml"
  },
  {
    "name": "두유(무당)",
    "category": "유제품",
    "unit": "ml",
    "amount": 190.0,
    "kcal": 76.0,
    "protein": 6.5,
    "carb": 4.0,
    "fat": 3.8,
    "meals": "아침,간식",
    "note": "1팩=190ml"
  },
  {
    "name": "된장",
    "category": "양념",
    "unit": "g",
    "amount": 10.0,
    "kcal": 22.0,
    "protein": 1.4,
    "carb": 2.8,
    "fat": 0.6,
    "meals": "조리용",
    "note": "1Ts=10g"
  },
  {
    "name": "고추장",
    "category": "양념",
    "unit": "g",
    "amount": 10.0,
    "kcal": 25.0,
    "protein": 0.9,
    "carb": 5.0,
    "fat": 0.2,
    "meals": "조리용",
    "note": "1Ts=10g"
  },
  {
    "name": "간장",
    "category": "양념",
    "unit": "ml",
    "amount": 10.0,
    "kcal": 6.0,
    "protein": 0.9,
    "carb": 0.6,
    "fat": 0.0,
    "meals": "조리용",
    "note": "1Ts=10ml"
  },
  {
    "name": "참기름",
    "category": "양념",
    "unit": "ml",
    "amount": 5.0,
    "kcal": 44.0,
    "protein": 0.0,
    "carb": 0.0,
    "fat": 5.0,
    "meals": "조리용",
    "note": "1ts=5ml"
  },
  {
    "name": "더단백드링크 다크초코",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 42.0,
    "protein": 8.0,
    "carb": 2.8,
    "fat": 0.2,
    "meals": "아침,간식",
    "note": "기준200g"
  },
  {
    "name": "차돌김치주먹밥",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 175.0,
    "protein": 5.0,
    "carb": 30.0,
    "fat": 3.9,
    "meals": "점심,저녁",
    "note": "기준100g"
  },
  {
    "name": "동경규동 (더이지)",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 133.0,
    "protein": 8.4,
    "carb": 9.4,
    "fat": 6.9,
    "meals": "점심,저녁",
    "note": "기준200g"
  },
  {
    "name": "들깨백순대볶음 (쿡솜씨)",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 143.0,
    "protein": 3.0,
    "carb": 26.0,
    "fat": 3.1,
    "meals": "점심,저녁",
    "note": "기준200g"
  },
  {
    "name": "더넛츠",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 635.0,
    "protein": 20.0,
    "carb": 25.0,
    "fat": 50.0,
    "meals": "간식",
    "note": "기준20g"
  },
  {
    "name": "바닐라크림빵 (노티드)",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 232.0,
    "protein": 2.9,
    "carb": 21.4,
    "fat": 17.1,
    "meals": "간식",
    "note": "기준140g"
  },
  {
    "name": "셀렉스 프로핏 초콜릿",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 30.0,
    "protein": 6.1,
    "carb": 0.9,
    "fat": 0.2,
    "meals": "아침,간식",
    "note": "기준200g"
  },
  {
    "name": "저지방우유 (1974)",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 45.0,
    "protein": 3.0,
    "carb": 5.0,
    "fat": 1.5,
    "meals": "아침,간식",
    "note": "기준200g"
  },
  {
    "name": "99칼로리칩 버터솔트",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 330.0,
    "protein": 16.5,
    "carb": 60.0,
    "fat": 6.5,
    "meals": "간식",
    "note": "기준20g"
  },
  {
    "name": "초코파이 (1983)",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 522.0,
    "protein": 15.7,
    "carb": 35.7,
    "fat": 34.3,
    "meals": "간식",
    "note": "기준30g"
  },
  {
    "name": "1등급 우유",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 65.0,
    "protein": 3.0,
    "carb": 4.6,
    "fat": 4.0,
    "meals": "아침,간식",
    "note": "기준200g"
  },
  {
    "name": "두부티라미수 녹차",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 233.0,
    "protein": 4.4,
    "carb": 25.6,
    "fat": 12.2,
    "meals": "디저트",
    "note": "기준200g"
  },
  {
    "name": "곤약볶음밥 갈비맛 (1am)",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 155.0,
    "protein": 7.0,
    "carb": 27.0,
    "fat": 2.0,
    "meals": "점심,저녁",
    "note": "기준200g"
  },
  {
    "name": "피스타치오",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 570.0,
    "protein": 20.0,
    "carb": 30.0,
    "fat": 45.0,
    "meals": "간식",
    "note": "기준20g"
  },
  {
    "name": "아몬드",
    "category": "가공식품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 544.0,
    "protein": 17.0,
    "carb": 40.0,
    "fat": 37.0,
    "meals": "간식",
    "note": "기준20g"
  },
  {
    "name": "닭다리살(생)",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 175.0,
    "protein": 18.5,
    "carb": 0.0,
    "fat": 10.8,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "닭날개(생)",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 198.0,
    "protein": 17.4,
    "carb": 0.0,
    "fat": 13.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "소고기 등심",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 218.0,
    "protein": 18.0,
    "carb": 0.0,
    "fat": 15.8,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "소고기 안심",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 168.0,
    "protein": 20.5,
    "carb": 0.0,
    "fat": 9.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "소고기 불고기용",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 143.0,
    "protein": 20.7,
    "carb": 0.0,
    "fat": 6.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "돼지고기 삼겹살",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 331.0,
    "protein": 17.0,
    "carb": 0.0,
    "fat": 29.0,
    "meals": "점심,저녁",
    "note": "자유식"
  },
  {
    "name": "돼지고기 목살",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 259.0,
    "protein": 17.5,
    "carb": 0.0,
    "fat": 20.8,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "돼지고기 앞다리",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 183.0,
    "protein": 20.0,
    "carb": 0.0,
    "fat": 11.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "닭가슴살 훈제",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 113.0,
    "protein": 22.0,
    "carb": 1.5,
    "fat": 1.8,
    "meals": "아침,점심,저녁,간식",
    "note": ""
  },
  {
    "name": "소시지(돼지)",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 321.0,
    "protein": 11.7,
    "carb": 3.2,
    "fat": 28.8,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "베이컨",
    "category": "육류",
    "unit": "g",
    "amount": 30.0,
    "kcal": 133.0,
    "protein": 5.7,
    "carb": 0.3,
    "fat": 12.3,
    "meals": "아침",
    "note": "3장=30g"
  },
  {
    "name": "오리고기(생)",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 201.0,
    "protein": 19.3,
    "carb": 0.0,
    "fat": 13.5,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "양고기(등심)",
    "category": "육류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 175.0,
    "protein": 20.0,
    "carb": 0.0,
    "fat": 10.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "오징어(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 88.0,
    "protein": 17.9,
    "carb": 1.0,
    "fat": 1.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "문어(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 82.0,
    "protein": 16.4,
    "carb": 1.4,
    "fat": 1.0,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "꽃게(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 76.0,
    "protein": 14.8,
    "carb": 1.3,
    "fat": 0.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "전복(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 96.0,
    "protein": 17.1,
    "carb": 6.0,
    "fat": 0.5,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "굴(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 59.0,
    "protein": 9.5,
    "carb": 3.7,
    "fat": 1.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "조개(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 64.0,
    "protein": 10.5,
    "carb": 3.0,
    "fat": 1.0,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "바지락(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 53.0,
    "protein": 9.3,
    "carb": 2.5,
    "fat": 0.7,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "참치(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 136.0,
    "protein": 23.3,
    "carb": 0.0,
    "fat": 4.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "갈치(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 176.0,
    "protein": 17.8,
    "carb": 0.0,
    "fat": 11.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "동태(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 78.0,
    "protein": 17.4,
    "carb": 0.0,
    "fat": 0.5,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "임연수(생)",
    "category": "해산물",
    "unit": "g",
    "amount": 100.0,
    "kcal": 123.0,
    "protein": 19.2,
    "carb": 0.0,
    "fat": 5.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "멸치(건)",
    "category": "해산물",
    "unit": "g",
    "amount": 15.0,
    "kcal": 52.0,
    "protein": 9.4,
    "carb": 0.2,
    "fat": 1.4,
    "meals": "반찬,간식",
    "note": "1줌=15g"
  },
  {
    "name": "미역(건)",
    "category": "해산물",
    "unit": "g",
    "amount": 10.0,
    "kcal": 14.0,
    "protein": 1.3,
    "carb": 2.5,
    "fat": 0.1,
    "meals": "점심,저녁",
    "note": "불린후=100g"
  },
  {
    "name": "김(구운)",
    "category": "해산물",
    "unit": "g",
    "amount": 5.0,
    "kcal": 16.0,
    "protein": 1.8,
    "carb": 1.2,
    "fat": 0.5,
    "meals": "점심,저녁",
    "note": "1장=5g"
  },
  {
    "name": "고추(풋)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 28.0,
    "protein": 1.5,
    "carb": 5.2,
    "fat": 0.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "마늘(생)",
    "category": "채소",
    "unit": "g",
    "amount": 10.0,
    "kcal": 14.0,
    "protein": 0.6,
    "carb": 3.0,
    "fat": 0.1,
    "meals": "조리용",
    "note": "1알=5g"
  },
  {
    "name": "생강(생)",
    "category": "채소",
    "unit": "g",
    "amount": 10.0,
    "kcal": 8.0,
    "protein": 0.2,
    "carb": 1.7,
    "fat": 0.1,
    "meals": "조리용",
    "note": ""
  },
  {
    "name": "대파(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 33.0,
    "protein": 1.9,
    "carb": 6.1,
    "fat": 0.3,
    "meals": "조리용,점심,저녁",
    "note": ""
  },
  {
    "name": "애호박(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 17.0,
    "protein": 1.1,
    "carb": 2.9,
    "fat": 0.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "가지(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 23.0,
    "protein": 1.0,
    "carb": 4.5,
    "fat": 0.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "고구마순(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 35.0,
    "protein": 2.5,
    "carb": 6.5,
    "fat": 0.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "깻잎(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 55.0,
    "protein": 4.8,
    "carb": 7.7,
    "fat": 0.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "부추(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 34.0,
    "protein": 2.8,
    "carb": 5.3,
    "fat": 0.5,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "콩나물(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 30.0,
    "protein": 3.2,
    "carb": 2.5,
    "fat": 1.0,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "숙주나물(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 20.0,
    "protein": 2.0,
    "carb": 2.3,
    "fat": 0.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "느타리버섯",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 27.0,
    "protein": 2.5,
    "carb": 4.5,
    "fat": 0.4,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "표고버섯(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 37.0,
    "protein": 2.7,
    "carb": 7.2,
    "fat": 0.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "아스파라거스",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 23.0,
    "protein": 2.4,
    "carb": 3.9,
    "fat": 0.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "셀러리(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 14.0,
    "protein": 0.6,
    "carb": 2.6,
    "fat": 0.2,
    "meals": "간식,저녁",
    "note": ""
  },
  {
    "name": "비트(생)",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 43.0,
    "protein": 1.6,
    "carb": 9.6,
    "fat": 0.1,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "적양배추",
    "category": "채소",
    "unit": "g",
    "amount": 100.0,
    "kcal": 27.0,
    "protein": 1.5,
    "carb": 5.5,
    "fat": 0.2,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "딸기(생)",
    "category": "과일",
    "unit": "g",
    "amount": 100.0,
    "kcal": 33.0,
    "protein": 0.7,
    "carb": 7.7,
    "fat": 0.3,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "블루베리(생)",
    "category": "과일",
    "unit": "g",
    "amount": 100.0,
    "kcal": 57.0,
    "protein": 0.7,
    "carb": 14.5,
    "fat": 0.3,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "수박(생)",
    "category": "과일",
    "unit": "g",
    "amount": 200.0,
    "kcal": 62.0,
    "protein": 1.2,
    "carb": 15.2,
    "fat": 0.2,
    "meals": "간식",
    "note": "1쪽=200g"
  },
  {
    "name": "포도(생)",
    "category": "과일",
    "unit": "g",
    "amount": 100.0,
    "kcal": 65.0,
    "protein": 0.6,
    "carb": 16.7,
    "fat": 0.3,
    "meals": "간식",
    "note": ""
  },
  {
    "name": "복숭아(생)",
    "category": "과일",
    "unit": "g",
    "amount": 150.0,
    "kcal": 63.0,
    "protein": 1.2,
    "carb": 15.0,
    "fat": 0.2,
    "meals": "간식",
    "note": "1개=150g"
  },
  {
    "name": "귤(생)",
    "category": "과일",
    "unit": "g",
    "amount": 100.0,
    "kcal": 46.0,
    "protein": 0.8,
    "carb": 11.1,
    "fat": 0.2,
    "meals": "간식",
    "note": "1개=100g"
  },
  {
    "name": "오렌지(생)",
    "category": "과일",
    "unit": "g",
    "amount": 150.0,
    "kcal": 70.0,
    "protein": 1.4,
    "carb": 16.5,
    "fat": 0.2,
    "meals": "간식",
    "note": "1개=150g"
  },
  {
    "name": "키위(생)",
    "category": "과일",
    "unit": "g",
    "amount": 80.0,
    "kcal": 45.0,
    "protein": 0.9,
    "carb": 10.6,
    "fat": 0.3,
    "meals": "아침,간식",
    "note": "1개=80g"
  },
  {
    "name": "망고(생)",
    "category": "과일",
    "unit": "g",
    "amount": 100.0,
    "kcal": 65.0,
    "protein": 0.5,
    "carb": 17.0,
    "fat": 0.3,
    "meals": "간식",
    "note": ""
  },
  {
    "name": "체리(생)",
    "category": "과일",
    "unit": "g",
    "amount": 100.0,
    "kcal": 63.0,
    "protein": 1.1,
    "carb": 16.0,
    "fat": 0.2,
    "meals": "간식",
    "note": ""
  },
  {
    "name": "파인애플(생)",
    "category": "과일",
    "unit": "g",
    "amount": 100.0,
    "kcal": 50.0,
    "protein": 0.5,
    "carb": 13.1,
    "fat": 0.1,
    "meals": "간식",
    "note": ""
  },
  {
    "name": "자몽(생)",
    "category": "과일",
    "unit": "g",
    "amount": 200.0,
    "kcal": 82.0,
    "protein": 1.6,
    "carb": 20.8,
    "fat": 0.2,
    "meals": "아침,간식",
    "note": "1개=200g"
  },
  {
    "name": "달걀노른자",
    "category": "유제품",
    "unit": "g",
    "amount": 60.0,
    "kcal": 195.0,
    "protein": 8.7,
    "carb": 1.0,
    "fat": 17.5,
    "meals": "아침",
    "note": "1개 노른자=20g"
  },
  {
    "name": "코티지치즈",
    "category": "유제품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 98.0,
    "protein": 11.1,
    "carb": 3.4,
    "fat": 4.3,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "리코타치즈",
    "category": "유제품",
    "unit": "g",
    "amount": 50.0,
    "kcal": 82.0,
    "protein": 4.8,
    "carb": 2.5,
    "fat": 6.3,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "모짜렐라치즈",
    "category": "유제품",
    "unit": "g",
    "amount": 30.0,
    "kcal": 80.0,
    "protein": 5.5,
    "carb": 0.6,
    "fat": 6.1,
    "meals": "간식",
    "note": ""
  },
  {
    "name": "파마산치즈(분말)",
    "category": "유제품",
    "unit": "g",
    "amount": 10.0,
    "kcal": 43.0,
    "protein": 3.9,
    "carb": 0.4,
    "fat": 2.9,
    "meals": "조리용",
    "note": "1Ts=10g"
  },
  {
    "name": "전지우유",
    "category": "유제품",
    "unit": "ml",
    "amount": 200.0,
    "kcal": 130.0,
    "protein": 6.6,
    "carb": 9.2,
    "fat": 7.2,
    "meals": "아침,간식",
    "note": "1컵=200ml"
  },
  {
    "name": "무지방우유",
    "category": "유제품",
    "unit": "ml",
    "amount": 200.0,
    "kcal": 70.0,
    "protein": 7.0,
    "carb": 9.4,
    "fat": 0.4,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "그릭요거트(일반)",
    "category": "유제품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 97.0,
    "protein": 9.0,
    "carb": 3.6,
    "fat": 5.0,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "케피어",
    "category": "유제품",
    "unit": "ml",
    "amount": 200.0,
    "kcal": 130.0,
    "protein": 8.0,
    "carb": 10.0,
    "fat": 4.0,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "순두부",
    "category": "유제품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 38.0,
    "protein": 4.1,
    "carb": 1.0,
    "fat": 1.8,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "연두부",
    "category": "유제품",
    "unit": "g",
    "amount": 100.0,
    "kcal": 42.0,
    "protein": 4.3,
    "carb": 1.5,
    "fat": 2.0,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "두유(고단백)",
    "category": "유제품",
    "unit": "ml",
    "amount": 190.0,
    "kcal": 100.0,
    "protein": 9.5,
    "carb": 5.0,
    "fat": 4.0,
    "meals": "아침,간식",
    "note": ""
  },
  {
    "name": "퀴노아(익힌)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 120.0,
    "protein": 4.1,
    "carb": 21.3,
    "fat": 1.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "현미(생)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 356.0,
    "protein": 7.4,
    "carb": 74.9,
    "fat": 2.7,
    "meals": "점심,저녁",
    "note": "밥=160kcal/100g"
  },
  {
    "name": "보리(익힌)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 123.0,
    "protein": 2.3,
    "carb": 28.2,
    "fat": 0.4,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "귀리(생)",
    "category": "곡류",
    "unit": "g",
    "amount": 50.0,
    "kcal": 193.0,
    "protein": 8.5,
    "carb": 33.0,
    "fat": 3.5,
    "meals": "아침",
    "note": "1회=50g"
  },
  {
    "name": "통밀(생)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 339.0,
    "protein": 13.7,
    "carb": 72.0,
    "fat": 2.5,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "메밀(생)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 343.0,
    "protein": 13.3,
    "carb": 71.5,
    "fat": 3.4,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "잡곡(혼합)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 350.0,
    "protein": 9.0,
    "carb": 73.0,
    "fat": 2.5,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "식빵(흰)",
    "category": "곡류",
    "unit": "g",
    "amount": 30.0,
    "kcal": 80.0,
    "protein": 2.6,
    "carb": 14.9,
    "fat": 1.1,
    "meals": "아침",
    "note": "1장=30g"
  },
  {
    "name": "호밀빵",
    "category": "곡류",
    "unit": "g",
    "amount": 30.0,
    "kcal": 69.0,
    "protein": 2.6,
    "carb": 13.3,
    "fat": 0.8,
    "meals": "아침",
    "note": "1장=30g"
  },
  {
    "name": "베이글(플레인)",
    "category": "곡류",
    "unit": "g",
    "amount": 90.0,
    "kcal": 250.0,
    "protein": 9.0,
    "carb": 49.0,
    "fat": 1.5,
    "meals": "아침",
    "note": "1개=90g"
  },
  {
    "name": "크래커(통곡물)",
    "category": "곡류",
    "unit": "g",
    "amount": 20.0,
    "kcal": 80.0,
    "protein": 2.0,
    "carb": 13.5,
    "fat": 2.0,
    "meals": "간식",
    "note": "5개=20g"
  },
  {
    "name": "쌀면(익힌)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 113.0,
    "protein": 1.8,
    "carb": 25.2,
    "fat": 0.3,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "파스타(익힌)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 157.0,
    "protein": 5.8,
    "carb": 30.9,
    "fat": 0.9,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "우동면(익힌)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 132.0,
    "protein": 3.3,
    "carb": 27.4,
    "fat": 0.4,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "냉면(건면)",
    "category": "곡류",
    "unit": "g",
    "amount": 100.0,
    "kcal": 343.0,
    "protein": 7.8,
    "carb": 76.5,
    "fat": 1.0,
    "meals": "점심,저녁",
    "note": ""
  },
  {
    "name": "고구마말랭이",
    "category": "곡류",
    "unit": "g",
    "amount": 30.0,
    "kcal": 101.0,
    "protein": 1.2,
    "carb": 24.5,
    "fat": 0.1,
    "meals": "간식",
    "note": "1봉=30g"
  }
];

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const { q, category, meal } = req.query;
  let result = FOODS;

  if (category) result = result.filter(f => f.category === category);
  if (meal) result = result.filter(f => f.meals.includes(meal));
  if (q) {
    const query = q.toLowerCase();
    result = result.filter(f => f.name.toLowerCase().includes(query));
  }

  return res.status(200).json({ foods: result, total: result.length });
};
